apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitrixdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitrix
  template:
    metadata:
      labels:
        app: bitrix
    spec:
      containers:
      - name: bitrix
        image: nginx
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
        ports:
        - containerPort: 80
