apiVersion: v1
kind: Pod 
metadata:
  name: "mydb3"
  labels:
    app: mydb 
speec:
  containers:
  - name: "mydb3"
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_USER
      value: vimal
    - name: MYSQL_PASS 
      value: redhat
    - name: MYSQL_DATABASE
      value: wpdb
